name: my-first-symfony-app
recipe: symfony
config:
  webroot: public
  php: '8.0'
  via: apache
  ssl: true
  xdebug: true
  build:
    - composer self-update
    - composer install

  db:
    type: mariadb:10.5.9
    portforward: 37001
    creds:
      database: sfgroup_demo
      user: mariadb
      password: mariadb