name: demo

proxy:
  api:
    - api.demo.lndo.site
  mailhog:
    - mail.demo.lndo.site

services:
  api:
    type: php:8.0
    via: apache
    webroot: public
    ssl: true
    xdebug: true
    build:
      - composer self-update
      - composer install
  db:
    type: mariadb:10.5.9
    portforward: 37030
    creds:
      database: sf_user_group_demo
      user: mariadb
      password: mariadb

  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - api